/*
AUTOGENERATED - DON'T EDIT
Your edits in this file will be overwritten in the next build!
Modify the docusaurus.config.js file at your site's root instead.
*/
export default {
  "title": "Apache BookKeeper",
  "url": "https://bookkeeper.apache.org",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "organizationName": "apache",
  "projectName": "bookkeeper",
  "plugins": [
    "docusaurus-plugin-sass"
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/Users/nicolo.boschi/dev/bookkeeper/site3/website/sidebars.json",
          "breadcrumbs": false
        },
        "blog": {
          "showReadingTime": true
        },
        "theme": {
          "customCss": "/Users/nicolo.boschi/dev/bookkeeper/site3/website/src/sass/index.scss"
        }
      }
    ]
  ],
  "themeConfig": {
    "navbar": {
      "title": "Apache BookKeeper",
      "logo": {
        "alt": "Apache Bookkeeper",
        "src": "img/bk-logo.svg"
      },
      "items": [
        {
          "type": "doc",
          "docId": "overview/overview",
          "position": "left",
          "label": "Documentation"
        },
        {
          "position": "left",
          "label": "Community",
          "items": [
            {
              "label": "Mailing lists",
              "to": "community/mailing-lists"
            },
            {
              "label": "Slack",
              "to": "community/slack"
            },
            {
              "label": "Github issues",
              "href": "https://github.com/apache/bookkeeper/issues"
            },
            {
              "label": "Release management",
              "to": "community/releases"
            },
            {
              "label": "Community meetings",
              "to": "community/meeting"
            },
            {
              "label": "Contribution guide",
              "to": "community/contributing"
            },
            {
              "label": "Coding guide",
              "to": "community/coding-guide"
            },
            {
              "label": "Testing guide",
              "to": "community/testing"
            },
            {
              "label": "Issue report guide",
              "to": "community/issue-report"
            },
            {
              "label": "Release guide",
              "to": "community/release-guide"
            },
            {
              "label": "Presentations",
              "to": "community/presentations"
            },
            {
              "label": "BookKeeper proposals (BP)",
              "to": "community/bookkeeper-proposals"
            }
          ]
        },
        {
          "position": "left",
          "label": "Project",
          "items": [
            {
              "label": "Who are we?",
              "to": "project/who"
            },
            {
              "label": "Bylaws",
              "to": "project/bylaws"
            },
            {
              "label": "License",
              "href": "https://apache.org/licenses"
            },
            {
              "label": "Privacy policy",
              "to": "project/privacy"
            },
            {
              "label": "Sponsorship",
              "href": "https://www.apache.org/foundation/sponsorship.html"
            },
            {
              "label": "Thanks",
              "href": "https://www.apache.org/foundation/thanks.html"
            }
          ]
        },
        {
          "type": "docsVersionDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        },
        {
          "to": "releases",
          "label": "Download",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "copyright": "<footer class=\"footer\">\n        <div class=\"container\">\n          <div class=\"content has-text-centered\">\n            <p>\n              Copyright &copy; 2016 - 2022 <a href=\"https://www.apache.org/\">The Apache Software Foundation</a>,<br /> licensed under the <a href=\"http://www.apache.org/licenses/LICENSE-2.0\">Apache License, version 2.0</a>.\n            </p>\n            <p>\n              Apache BookKeeper, BookKeeper®, Apache®, the Apache feature logo, and the Apache BookKeeper logo are either registered trademarks or trademarks of The Apache Software Foundation.\n            </p>\n          </div>\n        </div>\n      </footer>\n      ",
      "links": [
        {
          "title": "Documentation",
          "items": [
            {
              "label": "Overview",
              "to": "docs/overview"
            },
            {
              "label": "Getting started",
              "to": "docs/getting-started/installation"
            },
            {
              "label": "Deployment",
              "to": "docs/deployment/manual"
            },
            {
              "label": "Administration",
              "to": "docs/admin/bookies"
            },
            {
              "label": "API",
              "to": "docs/api/overview"
            },
            {
              "label": "Security",
              "to": "docs/security/overview"
            },
            {
              "label": "Development",
              "to": "docs/development/protocol"
            },
            {
              "label": "Reference",
              "to": "docs/reference/config"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Mailing lists",
              "to": "community/mailing-lists"
            },
            {
              "label": "Slack",
              "to": "community/slack"
            },
            {
              "label": "Github",
              "href": "https://github.com/apache/bookkeeper"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/asfbookkeeper"
            }
          ]
        },
        {
          "title": "Project",
          "items": [
            {
              "label": "Who are we?",
              "to": "project/who"
            },
            {
              "label": "Bylaws",
              "to": "project/bylaws"
            },
            {
              "label": "License",
              "href": "https://apache.org/licenses"
            },
            {
              "label": "Privacy policy",
              "to": "project/privacy"
            },
            {
              "label": "Sponsorship",
              "href": "https://www.apache.org/foundation/sponsorship.html"
            },
            {
              "label": "Thanks",
              "href": "https://www.apache.org/foundation/thanks.html"
            }
          ]
        }
      ]
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": []
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage"
    },
    "metadata": [],
    "hideableSidebar": false,
    "autoCollapseSidebarCategories": false,
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "customFields": {
    "latest_release": "4.14.4",
    "stable_release": "4.14.4",
    "github_repo": "https://github.com/apache/bookkeeper",
    "github_master": "https://github.com/apache/bookkeeper/tree/master",
    "mirror_base_url": "https://www.apache.org/dyn/closer.lua/bookkeeper",
    "dist_base_url": "https://www.apache.org/dist/bookkeeper",
    "archive_base_url": "https://archive.apache.org/dist/bookkeeper",
    "javadoc_base_url": "https://bookkeeper.apache.org/docs/latest/api/javadoc",
    "archive_releases_base_url": "https://bookkeeper.apache.org/archives"
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "themes": [],
  "tagline": "",
  "titleDelimiter": "|",
  "noIndex": false
};